# Default configuration for SISTER
# This file is installed with the package and should not be modified.
# Create a custom config file in ~/.sister_sto/config/config.yaml to override these settings.

# Logging settings
log_level: "WARNING"

# OCR settings
locate_labels:
  gpu: false

# Icon matching settings
prefilter_icons:
  method: "hash"

# Output transformation settings
output_transformation:
  transformations_enabled_list:
    - "BACKFILL_MATCHES_WITH_PREFILTERED"

# Engine settings
engine: "phash"
